#!/usr/bin/env python3
"""
Ensemble Interpolation Script

Generates ensembles of interpolated weather trajectories with flexible
conditioning.  Any subset of the 12 output frames (0-11) can be conditioned
on, and each conditioning frame can come from one of three sources:

  - ERA5 (default):    the corresponding frame from the start-time window,
                       NaN-padded to the full 45-variable model layout
  - Custom ERA5 frame: a NaN-padded ERA5 frame from a different date/time
  - TC guidance:       a frame generated by the TC guidance model

The ensemble_size parameter controls how many ensemble members are generated.
All members share the same conditioning but receive different stochastic
noise, producing diverse trajectories. Large ensembles are automatically
chunked into micro-batches of batch_size to fit in GPU memory.

Pipeline: Load raw ERA5 zarr data (lat/lon) -> Regrid to healpix and pad non-ERA5
          variables with NaN -> Interpolate with CBottleInterpolate
          (healpix in, healpix out) -> Save ensemble output as zarr stores
          on the native HEALPix grid; the ERA5 reference store stays on
          lat/lon for downstream regridding flexibility.
"""

import argparse
import os
import shutil
import sys
from datetime import datetime, timedelta

import numpy as np
import torch
import zarr

# Add scripts/_shared to path; its custom_utils symlink resolves the import.
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '_shared'))
from custom_utils.interpolation_utils import (  # noqa: E402
    STORED_VARIABLES,
    CBottleUtils,
    subset_variables,
)


# ============================================================================
# Argument Parser
# ============================================================================

def setup_args():
    """Setup command line arguments."""
    parser = argparse.ArgumentParser(
        description='Ensemble Interpolation: generate ensemble members with '
                    'flexible frame conditioning'
    )

    # Date/Time Configuration
    parser.add_argument('--start-year', type=int, required=True,
                        help='Start year for the 12-frame window')
    parser.add_argument('--start-month', type=int, required=True,
                        help='Start month (1-12)')
    parser.add_argument('--start-day', type=int, required=True,
                        help='Start day of month')
    parser.add_argument('--start-hour', type=int, default=0,
                        help='Start hour (0, 6, 12, or 18), default: 0')

    # Conditioning Frames (flexible)
    parser.add_argument('--conditioning-frames', type=str, required=True,
                        help='Comma-separated frame indices (0-11) to condition on, '
                             'e.g. "0,11" for both ends, "0" for start-only, '
                             '"0,3,6,11" for four frames')

    # Ensemble Configuration
    parser.add_argument('--ensemble-size', type=int, default=4,
                        help='Total number of ensemble members to generate, default: 4')
    parser.add_argument('--member-offset', type=int, default=0,
                        help='Offset from 0 for saving subset chunks. default: 0')
    parser.add_argument('--members-to-run', type=int, default=None,
                        help='Override the number of members generated by this specific job, default: matches ensemble_size')
    parser.add_argument('--batch-size', type=int, default=1,
                        help='Micro-batch size per forward pass (GPU limit), default: 1')
    parser.add_argument('--random-seed', type=int, default=None,
                        help='Random seed for model, default: None')

    # Output
    parser.add_argument('--output-dir', type=str, required=True,
                        help='Output directory for ensemble zarr stores')

    # Model Configuration
    parser.add_argument('--data-path', type=str,
                        default='/projectnb/eb-general/shared_data/data/raw/era5_raw_zarr',
                        help='Path to ERA5 raw zarr root directory')
    parser.add_argument('--package-timeout', type=int, default=600,
                        help='Package download timeout in seconds, default: 600')

    # Custom ERA5 frames (repeatable).  Each occurrence specifies one frame
    # whose conditioning data comes from an arbitrary ERA5 date instead of
    # the natural window.
    #   --custom-frame FRAME_IDX YEAR MONTH DAY HOUR
    parser.add_argument('--custom-frame', action='append', nargs=5,
                        metavar=('FRAME', 'YEAR', 'MONTH', 'DAY', 'HOUR'),
                        help='Custom ERA5 frame: FRAME_IDX YEAR MONTH DAY HOUR '
                             '(repeatable for multiple frames)')

    # TC guidance frames (repeatable).  Each occurrence specifies one frame
    # whose conditioning data is generated by the TC guidance model.
    # Latitudes and longitudes use colon separators within each argument
    # (commas are used by argparse for list items).
    #   --tc-frame FRAME_IDX LAT1,LAT2,... LON1,LON2,...
    parser.add_argument('--tc-frame', action='append', nargs=3,
                        metavar=('FRAME', 'LATS', 'LONS'),
                        help='TC guidance frame: FRAME_IDX LAT1,LAT2,... LON1,LON2,... '
                             '(repeatable for multiple frames)')

    return parser.parse_args()


# ============================================================================
# Helper Functions
# ============================================================================

def parse_conditioning_frames(frames_str):
    """Parse comma-separated frame indices into a sorted list of ints."""
    frames = sorted(int(x.strip()) for x in frames_str.split(','))
    for f in frames:
        if f < 0 or f > 11:
            raise ValueError(f"Frame index {f} out of range [0, 11]")
    if len(frames) != len(set(frames)):
        raise ValueError(f"Duplicate frame indices in: {frames_str}")
    return frames


def parse_custom_frame_specs(raw_specs):
    """Parse --custom-frame arguments into a dict keyed by frame index.

    Returns
    -------
    dict[int, tuple[int, int, int, int]]
        {frame_idx: (year, month, day, hour)}
    """
    specs = {}
    if not raw_specs:
        return specs
    for cf in raw_specs:
        frame_idx = int(cf[0])
        if frame_idx in specs:
            raise ValueError(
                f"Duplicate --custom-frame for frame index {frame_idx}"
            )
        specs[frame_idx] = (int(cf[1]), int(cf[2]), int(cf[3]), int(cf[4]))
    return specs


def parse_tc_frame_specs(raw_specs):
    """Parse --tc-frame arguments into a dict keyed by frame index.

    Returns
    -------
    dict[int, tuple[torch.Tensor, torch.Tensor]]
        {frame_idx: (lats_tensor, lons_tensor)}
    """
    specs = {}
    if not raw_specs:
        return specs
    for tf in raw_specs:
        frame_idx = int(tf[0])
        if frame_idx in specs:
            raise ValueError(
                f"Duplicate --tc-frame for frame index {frame_idx}"
            )
        lats = torch.tensor([float(x.strip()) for x in tf[1].split(',')])
        lons = torch.tensor([float(x.strip()) for x in tf[2].split(',')])
        if len(lats) != len(lons):
            raise ValueError(
                f"TC frame {frame_idx}: latitudes ({len(lats)}) and "
                f"longitudes ({len(lons)}) must have the same length"
            )
        specs[frame_idx] = (lats, lons)
    return specs


def validate_frame_specs(conditioning_frames, custom_specs, tc_specs):
    """Validate that custom and TC frame specs are consistent with conditioning frames.

    Each conditioning frame must come from exactly one source: default ERA5
    (NaN-padded), custom ERA5 (NaN-padded), or TC guidance.  This function
    enforces mutual exclusivity across all three sources.
    """
    for f in custom_specs:
        if f not in conditioning_frames:
            raise ValueError(
                f"Custom frame index {f} is not in conditioning_frames {conditioning_frames}"
            )
    for f in tc_specs:
        if f not in conditioning_frames:
            raise ValueError(
                f"TC frame index {f} is not in conditioning_frames {conditioning_frames}"
            )
    overlap = set(custom_specs) & set(tc_specs)
    if overlap:
        raise ValueError(
            f"Frame indices {overlap} cannot be both custom ERA5 and TC guidance"
        )
    # Verify every conditioning frame maps to exactly one source
    era5_set = set(conditioning_frames) - set(custom_specs) - set(tc_specs)
    assert era5_set | set(custom_specs) | set(tc_specs) == set(conditioning_frames), (
        f"Source sets do not cover all conditioning frames: "
        f"era5={era5_set}, custom={set(custom_specs)}, tc={set(tc_specs)}, "
        f"conditioning={set(conditioning_frames)}"
    )


def squeeze_tc_frame(tc_raw):
    """Normalize TC guidance output to shape [1, 1, C, H]."""
    tc_frame = tc_raw
    while tc_frame.ndim > 2:
        assert tc_frame.shape[0] == 1, (
            f"Expected singleton dimension but got shape {tc_frame.shape}"
        )
        tc_frame = tc_frame.squeeze(0)
    return tc_frame.unsqueeze(0).unsqueeze(0).cpu()


# ============================================================================
# Zarr I/O Helpers
# ============================================================================

_COMPRESSORS = zarr.codecs.BloscCodec(
    cname='zstd', clevel=2, shuffle=zarr.codecs.BloscShuffle.bitshuffle,
)


def save_era5_zarr(path, data_tensor, coords):
    """Save ERA5 reference data as a zarr store.

    Safe for concurrent callers. All chunked ensemble jobs share one
    output directory and would otherwise race on this path. Each writer
    builds its own ``path.tmp.<pid>`` and publishes it with a single
    ``os.rename``; the first to finish wins and later writers clean up.
    If ``path`` already holds a complete reference, the writer skips.

    Parameters
    ----------
    path : str
        Output path for the zarr store.
    data_tensor : torch.Tensor
        Shape ``[12, 1, 34, 721, 1440]``.
    coords : OrderedDict
        Coordinate arrays (time, lead_time, variable, lat, lon).
    """
    if os.path.exists(path):
        try:
            if zarr.open_group(str(path), mode='r').attrs.get("complete"):
                return
        except Exception:
            pass
        # Incomplete or corrupt — remove so our rename can land.
        shutil.rmtree(path, ignore_errors=True)

    tmp = f"{path}.tmp.{os.getpid()}"
    shutil.rmtree(tmp, ignore_errors=True)
    try:
        root = zarr.open_group(str(tmp), mode='w')
        shape = data_tensor.shape
        root.create_array(
            "data", shape=shape,
            chunks=(1, *shape[1:]),
            dtype=np.float32, compressors=_COMPRESSORS,
        )
        root["data"][:] = data_tensor.cpu().numpy()

        root.create_array("time", shape=coords["time"].shape, dtype=coords["time"].dtype)
        root["time"][:] = coords["time"]
        root.create_array("lead_time", shape=coords["lead_time"].shape, dtype=coords["lead_time"].dtype)
        root["lead_time"][:] = coords["lead_time"]
        root.create_array("variable", shape=coords["variable"].shape, dtype=str)
        root["variable"][:] = coords["variable"]
        root.create_array("lat", shape=coords["lat"].shape, dtype=np.float64)
        root["lat"][:] = coords["lat"]
        root.create_array("lon", shape=coords["lon"].shape, dtype=np.float64)
        root["lon"][:] = coords["lon"]

        root.attrs["description"] = "ERA5 reference data for interpolation"
        root.attrs["dimensions"] = ["time", "lead_time", "variable", "lat", "lon"]
        root.attrs["complete"] = True

        try:
            os.rename(tmp, path)
        except OSError:
            pass
    finally:
        if os.path.exists(tmp):
            shutil.rmtree(tmp, ignore_errors=True)


def create_ensemble_zarr(path, ensemble_size, member_shape, interp_coords, metadata):
    """Create a pre-allocated zarr store for ensemble output.

    Parameters
    ----------
    path : str
        Output path for the zarr store.
    ensemble_size : int
        Total number of ensemble members.
    member_shape : tuple
        Shape of a single ensemble member (e.g. ``(1, 12, 14, 49152)`` for HPX
        or ``(1, 12, 14, 721, 1440)`` for lat/lon).
    interp_coords : OrderedDict
        Coordinate arrays from the interpolation model.  Spatial coords can be
        ``"hpx"`` (native HEALPix output) or ``"lat"``/``"lon"`` (lat/lon
        output); whichever keys are present are written to the store.
    metadata : dict
        Metadata to store as zarr attrs.

    Returns
    -------
    root : zarr.Group
    data_array : zarr.Array
    """
    if os.path.exists(path):
        shutil.rmtree(path)

    root = zarr.open_group(str(path), mode='w')
    full_shape = (ensemble_size, *member_shape)
    # Blosc codec has a 2GB (2^31 - 1 bytes) buffer limit.  Chunk along the
    # lead_time axis so that each chunk stays safely below that limit.
    _BLOSC_MAX = 2_147_483_647  # 2^31 - 1
    chunk_shape = list((1, *member_shape))
    lt_axis = 2  # (ensemble, time, lead_time, variable, ...)
    elem_bytes = np.dtype(np.float32).itemsize
    while (np.prod(chunk_shape) * elem_bytes) > _BLOSC_MAX and chunk_shape[lt_axis] > 1:
        chunk_shape[lt_axis] = max(1, chunk_shape[lt_axis] // 2)
    data_array = root.create_array(
        "data", shape=full_shape,
        chunks=tuple(chunk_shape),
        dtype=np.float32, compressors=_COMPRESSORS,
    )

    # Time / lead_time / variable always have fixed dtypes; spatial coords
    # (lat/lon for lat/lon output, hpx for HEALPix output) are written
    # whichever keys are present in ``interp_coords``.
    root.create_array("time", shape=interp_coords["time"].shape, dtype=interp_coords["time"].dtype)
    root["time"][:] = interp_coords["time"]
    root.create_array("lead_time", shape=interp_coords["lead_time"].shape, dtype=interp_coords["lead_time"].dtype)
    root["lead_time"][:] = interp_coords["lead_time"]
    root.create_array("variable", shape=interp_coords["variable"].shape, dtype=str)
    root["variable"][:] = interp_coords["variable"]
    for key in interp_coords:
        if key in {"time", "lead_time", "variable"}:
            continue
        coord = np.asarray(interp_coords[key])
        root.create_array(key, shape=coord.shape, dtype=coord.dtype)
        root[key][:] = coord

    # Stash hpx_level alongside the pixel-index coord so loaders don't have to
    # re-derive it from len(hpx).  HEALPix has 12 * 4**level pixels.
    if "hpx" in interp_coords:
        n_pix = int(np.asarray(interp_coords["hpx"]).shape[0])
        level = int(np.log2(n_pix // 12) / 2)
        if 12 * 4**level != n_pix:
            raise ValueError(
                f"hpx coord length {n_pix} is not a valid HEALPix pixel count "
                f"(expected 12 * 4**level)"
            )
        root.attrs["hpx_level"] = level
        root.attrs["hpx_pixel_order"] = "NEST"

    for key, value in metadata.items():
        root.attrs[key] = value

    return root, data_array


# ============================================================================
# Main Function
# ============================================================================

def main(args):
    """Main execution function."""
    print("=" * 80)
    print("Ensemble Interpolation Pipeline")
    print("=" * 80)

    # --- Parse and validate ---
    conditioning_frames = parse_conditioning_frames(args.conditioning_frames)
    custom_specs = parse_custom_frame_specs(args.custom_frame)
    tc_specs = parse_tc_frame_specs(args.tc_frame)
    validate_frame_specs(conditioning_frames, custom_specs, tc_specs)

    # Frames sourced from the natural ERA5 window (not custom, not TC)
    era5_frames = [f for f in conditioning_frames
                   if f not in custom_specs and f not in tc_specs]

    frames_tag = "_".join(str(f) for f in conditioning_frames)
    os.makedirs(args.output_dir, exist_ok=True)
    utils = CBottleUtils(random_seed=args.random_seed, package_timeout=args.package_timeout)
    max_batch = min(args.batch_size, args.ensemble_size)

    print(f"Conditioning frames: {conditioning_frames}")
    if era5_frames:
        print(f"  ERA5 frames: {era5_frames}")
    if custom_specs:
        print(f"  Custom ERA5 frames: {dict(custom_specs)}")
    if tc_specs:
        print(f"  TC guidance frames: {list(tc_specs.keys())}")
    print(f"Total ensemble members: {args.ensemble_size}")
    print(f"Max micro-batch size: {max_batch}")

    # ------------------------------------------------------------------
    # Step 1: Load ERA5 data
    # ------------------------------------------------------------------
    print("\n--- Step 1: Loading ERA5 data ---")
    era5_data, era5_coords = utils.load_era5_zarr(
        args.data_path, args.start_year, args.start_month,
        args.start_day, args.start_hour,
    )
    print(f"ERA5 data shape: {era5_data.shape}")

    era5_save_path = os.path.join(args.output_dir, "era5_reference.zarr")
    era5_subset, era5_subset_coords = subset_variables(
        era5_data, era5_coords, STORED_VARIABLES,
    )
    save_era5_zarr(era5_save_path, era5_subset, era5_subset_coords)
    del era5_subset
    print(f"Saved ERA5 reference to {era5_save_path} "
          f"({len(era5_subset_coords['variable'])} variables)")

    # ------------------------------------------------------------------
    # Step 2: Regrid ERA5 to healpix + NaN-pad non-ERA5 variables, plus
    # any custom ERA5 frames from other dates/times.
    # ------------------------------------------------------------------
    print("\n--- Step 2: Regridding + NaN-padding ERA5 data ---")
    padded_data, padded_coords = utils.pad_era5_to_output(era5_data, era5_coords)
    del era5_data
    torch.cuda.empty_cache()
    padded_data = padded_data.cpu()
    print(f"Padded data shape: {padded_data.shape}")

    # Load custom ERA5 frames and pad non-ERA5 variables with NaN
    custom_frames_data = {}
    for frame_idx, (y, m, d, h) in custom_specs.items():
        print(f"\nLoading custom frame for index {frame_idx} "
              f"({y}-{m:02d}-{d:02d}T{h:02d}:00)...")
        frame_data = utils.load_and_pad_frame(
            args.data_path, y, m, d, h,
        )
        custom_frames_data[frame_idx] = frame_data
        print(f"  Custom frame shape: {frame_data.shape}")

    # ------------------------------------------------------------------
    # Step 2b: Generate TC guidance frames
    # ------------------------------------------------------------------
    tc_frames_data = {}
    if tc_specs:
        print("\n--- Step 2b: Generating TC guidance frames ---")
        tc_model = utils.load_tc_model()
        start_dt = datetime(
            args.start_year, args.start_month, args.start_day, args.start_hour
        )
        for frame_idx, (lats, lons) in tc_specs.items():
            tc_time = start_dt + timedelta(hours=frame_idx * 6)
            print(f"TC frame {frame_idx} at {tc_time} "
                  f"with {len(lats)} position(s)...")
            tc_raw, _ = utils.run_tc_guidance(tc_model, lats, lons, tc_time)
            tc_frames_data[frame_idx] = squeeze_tc_frame(tc_raw)
            print(f"  TC frame shape: {tc_frames_data[frame_idx].shape}")
        utils.free_model(tc_model)

    # ------------------------------------------------------------------
    # Step 3: Assemble conditioning data in frame order
    # ------------------------------------------------------------------
    print("\n--- Step 3: Assembling conditioning data ---")
    conditioning_parts = []
    for f in conditioning_frames:
        sources = (
            ("custom", f in custom_frames_data),
            ("tc", f in tc_frames_data),
            ("era5", f not in custom_frames_data and f not in tc_frames_data),
        )
        active = [name for name, hit in sources if hit]
        assert len(active) == 1, (
            f"Frame {f} matched {len(active)} sources ({active}); "
            f"expected exactly 1"
        )
        if f in custom_frames_data:
            conditioning_parts.append(custom_frames_data[f])
        elif f in tc_frames_data:
            conditioning_parts.append(tc_frames_data[f])
        else:
            conditioning_parts.append(padded_data[f:f + 1])

    conditioning_data = torch.cat(conditioning_parts, dim=0)
    print(f"Conditioning data shape: {conditioning_data.shape}")
    print(f"Conditioning frames: {conditioning_frames}")

    # Free intermediate data
    del padded_data, custom_frames_data, tc_frames_data

    # ------------------------------------------------------------------
    # Step 4: Run interpolation in micro-batches
    # ------------------------------------------------------------------
    print("\n--- Step 4: Running interpolation ---")
    interp_model = utils.load_interpolation_model(
        conditioning_frames=conditioning_frames,
        lat_lon=False,
        lat_lon_out=False,
    )

    output_filename = f"ensemble_f{frames_tag}_n{args.ensemble_size}.zarr"
    if args.member_offset > 0 or (args.members_to_run is not None and args.members_to_run < args.ensemble_size):
        output_filename = f"ensemble_f{frames_tag}_n{args.ensemble_size}_offset{args.member_offset}.zarr"
    ensemble_zarr_path = os.path.join(args.output_dir, output_filename)
    zarr_root = None
    zarr_data = None
    member_offset = 0

    members_to_run = args.members_to_run if args.members_to_run is not None else args.ensemble_size
    # Chunk jobs derive a global seed index from the offset; that only
    # produces non-overlapping indices when the offset aligns with the GPU
    # micro-batch size.  Enforce it here so misconfigured callers fail fast
    # instead of silently duplicating ensemble members.
    if args.member_offset % max_batch != 0:
        raise ValueError(
            f"--member-offset ({args.member_offset}) must be a multiple of "
            f"batch-size ({max_batch}) to keep per-chunk seeds unique."
        )
    remaining = members_to_run
    local_chunk_idx = 0
    base_seed = args.random_seed
    while remaining > 0:
        chunk_size = min(max_batch, remaining)
        print(f"\n  Micro-batch {local_chunk_idx} (Global offset {args.member_offset}): {chunk_size} members "
              f"({members_to_run - remaining}/{members_to_run} local members done)")

        # Use a different seed per chunk so each micro-batch produces
        # distinct ensemble members. Calculate a global chunk index.
        global_chunk_idx = (args.member_offset // max_batch) + local_chunk_idx
        if base_seed is not None:
            interp_model.seed = base_seed + global_chunk_idx

        x_cond, x_coords = utils.build_conditioning(
            conditioning_data, conditioning_frames, padded_coords,
            batch_size=chunk_size,
        )
        chunk_data, interp_coords = utils.run_interpolation(
            interp_model, x_cond, x_coords,
            conditioning_frames=conditioning_frames,
        )

        chunk_data, interp_coords = subset_variables(
            chunk_data, interp_coords, STORED_VARIABLES,
        )

        # Create zarr store on first chunk (to learn actual output shape)
        if zarr_root is None:
            member_shape = chunk_data.shape[1:]
            metadata = {
                "conditioning_frames": conditioning_frames,
                "ensemble_size": args.ensemble_size,
                "random_seed": args.random_seed,
                "start_date": f"{args.start_year}-{args.start_month:02d}-{args.start_day:02d}T{args.start_hour:02d}:00",
                "dimensions": ["ensemble", "time", "lead_time", "variable", "hpx"],
            }
            if custom_specs:
                metadata["custom_frames"] = {
                    str(k): f"{v[0]}-{v[1]:02d}-{v[2]:02d}T{v[3]:02d}:00"
                    for k, v in custom_specs.items()
                }
            if tc_specs:
                metadata["tc_frames"] = list(tc_specs.keys())
            zarr_root, zarr_data = create_ensemble_zarr(
                ensemble_zarr_path, members_to_run, member_shape,
                interp_coords, metadata,
            )

        chunk_np = chunk_data.cpu().numpy()

        # Write chunk directly into its zarr slice
        zarr_data[member_offset:member_offset + chunk_size] = chunk_np
        member_offset += chunk_size

        # Free GPU memory between chunks
        del x_cond, chunk_data, chunk_np
        torch.cuda.empty_cache()

        remaining -= chunk_size
        local_chunk_idx += 1

    zarr_root.attrs["complete"] = True
    utils.free_model(interp_model)
    del conditioning_data
    print(f"\nEnsemble output shape: {zarr_data.shape}")
    print(f"Saved ensemble output to {ensemble_zarr_path}")

    print("\n" + "=" * 80)
    print(f"All outputs saved to {args.output_dir}")
    print(f"  - era5_reference.zarr")
    print(f"  - {output_filename}")
    print("=" * 80)


if __name__ == "__main__":
    main(setup_args())
